### ISSUE TITLE
[UI] Homepage

### ISSUE THREAD

**Issue by hemant-mistry** [hemant-mistry/Travelify#17]
Main Screen UI changes
 
Welcome to travelify stays the same.
Under that  "Your go-to travel companion, here to help you explore the world" "Your trip, your way".
Get started stay the same with the coconut icon
 

![Image](https://github.com/user-attachments/assets/e49ab2e9-18dc-40b2-bb8d-13a29283cdb7)

Increase the font size of travelify logo as it should be prominent 

The ribbon should only contain my itinerary and user profile. 

The backgroud should be something like this if possible

![Image](https://github.com/user-attachments/assets/015a5a2b-8e6e-4f52-8d88-fd614d8be989)

This looks a little travel related. Although, this is too blue we need to add a mixture of all the colors mentioned below.

Our theme should be black, blue and green just like in the gemini logo.

If my itineraries icon can look something like this it will look good.

![Image](https://github.com/user-attachments/assets/657548d3-f7f1-4c8e-ae4c-6a759bd407b2)

**Comment by hemant-mistry** [comment]
If we change the HomePage to the above mentioned blue colour we might need to revamp the entire UI to align with that theme. Let me know your thoughts on it.

**Comment by Srane27** [comment]
I just want something like this which directly refers to travel lke the images in this.
The colors shoyld be a mix of black,green and blue. Just like gemini

**Comment by hemant-mistry** [comment]
Got it we can close on this.
